# Site wide configuration

title: "Gray Box Testing"
description: "Minimal testing with maximum benefit"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: "https://graybox-testing.org"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "David Fox"
  web: "https://dfox.io"
  twitter: "d_m_fox"
  bio: "Chief Architect at ThirdChannel"
  avatar: "bio-photo.jpg" # 160x160 px image for author byline

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - tmp
